### ISSUE TITLE
统一加’/‘前缀 无法跳转到插件页面

### ISSUE THREAD

**Issue by wiexin** [bigmeow/cheers-mp-router#8]
微信小程序插件页面的路由以“plugin://”开头，adapter方法会给每个路由统一加“/”前缀，导致找不到页面

**Comment by bigmeow** [comment]
> 微信小程序插件页面的路由以“plugin://”开头，adapter方法会给每个路由统一加“/”前缀，导致找不到页面

1.2.2 版本已经支持
